In [94]:
def function_name(parameters):
    """docstring"""
    statement(s)
    return value

def hello():
    """This function says hello and greets you"""
    print("Hello")
    print("Glad to meet you")

In [95]:
def find_square(num):
    result = num*num
    return result
square = find_square(3)
print('Square:', square)

Square: 9

In [96]:
x=lambda a : a + 10
print(x(5))

15

In [97]:
def calculate_carbon_footprint(energy_consumption, emmision_factor):
    """
    This function calculates the carbon footprint based on energy consumption (in kilowatt-hours) and the emmision factor (in kg CO2 per kwh)
    """
    return energy_consumption * emmision_factor

In [98]:
energy_consumption = 1000 
emission_factor = 0.475
carbon_footprint = calculate_carbon_footprint(energy_consumption, emission_factor)
print(f"Carbon FootprintL {carbon_footprint} kg CO2")

Carbon FootprintL 475.0 kg CO2

In [99]:
cities=[
    {"name": "City A", "carbon_footprint": 500},
    {"name": "City B", "carbon_footprint": 350},
    {"name": "City C", "carbon_footprint": 600},
    {"name": "City D", "carbon_footprint": 200},
]

sustainability_threshold = 400
sustainable_cities=list(filter(lambda city: city["carbon_footprint"] < sustainability_threshold, cities))

print("sustainable cities:")
for city in sustainable_cities:
    print(city["name"])

sustainable cities:
City B
City D

In [100]:
import pandas as pd
df = pd.read_csv('data.csv')
df.head()
df.describe()
df['Name']
df.loc[0]
#filters rows where age is greater than 25
filtered_df = df[df['age'] > 25]
df['Age_in_5_years'] = df['age'] + 5
grouped = df.groupby('Name').mean()

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [123]:
renewable_sources = ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass"]
data = {
    "Project": ["Solar Farm A", "wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "eothermal"],
    "Capacity (MW0)": [150, 300, 200, 50, 100],
    "cost (Million $)": [200, 400, 350, 100, 250],
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025,2023]
}

In [125]:
data

{'Project': ['Solar Farm A',
  'wind Turbine X',
  'Hydropower Y',
  'Solar Roof Z',
  'Geothermal Plant P'],
 'Technology': ['Solar', 'Wind', 'Hydropower', 'Solar', 'eothermal'],
 'Capacity (MW0)': [150, 300, 200, 50, 100],
 'cost (Million $)': [200, 400, 350, 100, 250],
 'Location': ['California', 'Texas', 'Washington', 'Nevada', 'Idaho'],
 'Completion Year': [2023, 2024, 2022, 2025, 2023]}

In [127]:
#create a panda series for renewable sources
renewable_series = pd.Series(renewable_sources)
print("Renewable Energy Sources:")
print(renewable_series)

Renewable Energy Sources:
0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object

In [129]:
#create a dataframe for green technology projects 
projects_df = pd.DataFrame(data)
print("\nGreen Technology Projects DataFrame:")
print(projects_df)

Green Technology Projects DataFrame:
              Project  Technology  Capacity (MW0)  cost (Million $)  \
0        Solar Farm A       Solar             150               200
1      wind Turbine X        Wind             300               400
2        Hydropower Y  Hydropower             200               350
3        Solar Roof Z       Solar              50               100
4  Geothermal Plant P   eothermal             100               250

     Location  Completion Year
0  California             2023
1       Texas             2024
2  Washington             2022
3      Nevada             2025
4       Idaho             2023

In [131]:
projects_df.head(2)

,Project,Technology,Capacity (MW0),cost (Million $),Location,Completion Year
0,Solar Farm A,Solar,150,200,California,2023
1,wind Turbine X,Wind,300,400,Texas,2024

In [133]:
projects_df.tail(2)

,Project,Technology,Capacity (MW0),cost (Million $),Location,Completion Year
3,Solar Roof Z,Solar,50,100,Nevada,2025
4,Geothermal Plant P,eothermal,100,250,Idaho,2023

In [135]:
projects_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW0)    5 non-null      int64
 3   cost (Million $)  5 non-null      int64
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes

In [137]:
projects_df.describe()

       Capacity (MW0)  cost (Million $)  Completion Year
count         5.00000          5.000000         5.000000
mean        160.00000        260.000000      2023.400000
std          96.17692        119.373364         1.140175
min          50.00000        100.000000      2022.000000
25%         100.00000        200.000000      2023.000000
50%         150.00000        250.000000      2023.000000
75%         200.00000        350.000000      2024.000000
max         300.00000        400.000000      2025.000000

In [139]:
projects_df.describe(include='all')

,Project,Technology,Capacity (MW0),cost (Million $),Location,Completion Year
count,5,5,5.00000,5.000000,5,5.000000
unique,5,4,NaN,NaN,5,NaN
top,Solar Farm A,Solar,NaN,NaN,California,NaN
freq,1,2,NaN,NaN,1,NaN
mean,NaN,NaN,160.00000,260.000000,NaN,2023.400000
std,NaN,NaN,96.17692,119.373364,NaN,1.140175
min,NaN,NaN,50.00000,100.000000,NaN,2022.000000
25%,NaN,NaN,100.00000,200.000000,NaN,2023.000000
50%,NaN,NaN,150.00000,250.000000,NaN,2023.000000
75%,NaN,NaN,200.00000,350.000000,NaN,2024.000000
max,NaN,NaN,300.00000,400.000000,NaN,2025.000000

In [141]:
projects_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Capacity (MW0),5.0,160.0,96.176920,50.0,100.0,150.0,200.0,300.0
cost (Million $),5.0,260.0,119.373364,100.0,200.0,250.0,350.0,400.0
Completion Year,5.0,2023.4,1.140175,2022.0,2023.0,2023.0,2024.0,2025.0

In [143]:
print("\nList of Projects:")
print(projects_df["Project"])

List of Projects:
0          Solar Farm A
1        wind Turbine X
2          Hydropower Y
3          Solar Roof Z
4    Geothermal Plant P
Name: Project, dtype: object

In [145]:
projects_df["Project"]

0          Solar Farm A
1        wind Turbine X
2          Hydropower Y
3          Solar Roof Z
4    Geothermal Plant P
Name: Project, dtype: object

In [147]:
high_capacity_projects = projects_df[projects_df["Capacity (MW0)"] > 100]
print("\nProjects with Capacity Greater than 100 MW:")
print(high_capacity_projects)

Projects with Capacity Greater than 100 MW:
          Project  Technology  Capacity (MW0)  cost (Million $)    Location  \
0    Solar Farm A       Solar             150               200  California
1  wind Turbine X        Wind             300               400       Texas
2    Hydropower Y  Hydropower             200               350  Washington

   Completion Year
0             2023
1             2024
2             2022

In [149]:
projects_df["Project"]

0          Solar Farm A
1        wind Turbine X
2          Hydropower Y
3          Solar Roof Z
4    Geothermal Plant P
Name: Project, dtype: object

In [151]:
projects_df.columns

Index(['Project', 'Technology', 'Capacity (MW0)', 'cost (Million $)',
       'Location', 'Completion Year'],
      dtype='object')

In [153]:
projects_df.shape

(5, 6)

In [155]:
projects_df.axes

[RangeIndex(start=0, stop=5, step=1),
 Index(['Project', 'Technology', 'Capacity (MW0)', 'cost (Million $)',
        'Location', 'Completion Year'],
       dtype='object')]

In [157]:
projects_df.isnull().sum()

Project             0
Technology          0
Capacity (MW0)      0
cost (Million $)    0
Location            0
Completion Year     0
dtype: int64

In [159]:
projects_df.isnull().sum().sum()

0

In [161]:
projects_df["Cost per MW"] = projects_df["cost (Million $)"] / projects_df["Capacity (MW0)"]
print("\nDataFrame with Cost per MW:")
print(projects_df)

DataFrame with Cost per MW:
              Project  Technology  Capacity (MW0)  cost (Million $)  \
0        Solar Farm A       Solar             150               200
1      wind Turbine X        Wind             300               400
2        Hydropower Y  Hydropower             200               350
3        Solar Roof Z       Solar              50               100
4  Geothermal Plant P   eothermal             100               250

     Location  Completion Year  Cost per MW
0  California             2023     1.333333
1       Texas             2024     1.333333
2  Washington             2022     1.750000
3      Nevada             2025     2.000000
4       Idaho             2023     2.500000

In [163]:
total_capacity = projects_df["Capacity (MW0)"].sum()
total_cost = projects_df["cost (Million $)"].sum()
print(f"\ntotal Cost of all projects: {total_capacity} MW0")
print(f"Total Cost of all projects: ${total_cost} million")

total Cost of all projects: 800 MW0
Total Cost of all projects: $1300 million

In [165]:
grouped_data = projects_df.groupby("Technology")["Capacity (MW0)"].sum()
print("\nTotal Capacity by Technology:")
print(grouped_data)

Total Capacity by Technology:
Technology
Hydropower    200
Solar         200
Wind          300
eothermal     100
Name: Capacity (MW0), dtype: int64

In [169]:
import numpy as np
a = np.array([0,1,2,3])#create a rank 1 array
print(a)               #print array a
print(type(a))        #type of array
print(a.ndim)         #dimension ofarray a
print(a.shape)       #shape of array
print(len(a))       #length of arrat

[0 1 2 3]
<class 'numpy.ndarray'>
1
(4,)
4

In [181]:
#create 2-D array using numpy from list
import numpy as np
mylist=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
np.random.rand(5)   #uniform distribution of random
np.random.rand(4,4) #create 2-D array of random
np.random.randn(4) #std. normal distribution

array([ 1.21304951, -1.0130167 ,  0.13279414,  1.67641193])

In [185]:
np.random.randint(0,10,1) #generate a random integer

array([9])

In [187]:
np.power(5,2)

25

In [189]:
np.sqrt(1)

1.0

In [193]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [195]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [209]:
np.max(a)

3

In [211]:
np.unique(5)

array([5])

In [217]:
np.dot(3,5)

15

In [215]:
#energy consumption in MWh for different renewable sources
energy_consumption = np.array([1200,3400,2900,1800,2500])
print("Eenergy Consumption in MWh for different renewable sources:")
print(energy_consumption)

Eenergy Consumption in MWh for different renewable sources:
[1200 3400 2900 1800 2500]

In [219]:
total_consumption = np.sum(energy_consumption)
print(f"\nTotal Energy Consumption: {total_consumption} MWh")

Total Energy Consumption: 11800 MWh

In [221]:
mean_consumption = np.mean(energy_consumption)
print(f"\nMean Energy Consumption: {mean_consumption:.2f} MWh")

Mean Energy Consumption: 2360.00 MWh

In [223]:
std_deviation = np.std(energy_consumption)
print(f"\nStandard Deviation of Energy consumption: {std_deviation:.2f} MWh")

Standard Deviation of Energy consumption: 781.28 MWh

In [227]:
#reshape the array 
reshaped_array = energy_consumption.reshape((5,1))
print("\nReshaped Energy Consumption Array (5x1):")
print(reshaped_array)

Reshaped Energy Consumption Array (5x1):
[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]